# Generated by Django 3.1.2 on 2020-10-20 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='itinerary',
        ),
        migrations.AddField(
            model_name='day',
            name='trip_itin',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='trip_itin', to='Trips.trip'),
        ),
        migrations.CreateModel(
            name='DayAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_def', models.CharField(default='', max_length=200)),
                ('action_time', models.CharField(default='', max_length=200)),
                ('day_itin', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='day_itin', to='Trips.day')),
            ],
        ),
    ]
