# Generated by Django 3.1.2 on 2020-10-20 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0002_auto_20201020_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='trip_itin',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Trips.trip'),
        ),
        migrations.DeleteModel(
            name='DayAction',
        ),
    ]
