# Generated by Django 3.1.2 on 2020-10-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0003_auto_20201020_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='destination',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='day',
            name='start_location',
            field=models.CharField(default='', max_length=30),
        ),
    ]
