# Generated by Django 3.1.2 on 2020-10-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0006_auto_20201020_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_user',
            field=models.CharField(default='', max_length=30),
        ),
    ]
