# Generated by Django 3.1.2 on 2020-10-20 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0010_auto_20201020_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_def', models.CharField(default='', max_length=200)),
                ('action_time', models.CharField(default='', max_length=200)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trips.day')),
            ],
        ),
    ]
