# Generated by Django 3.1.2 on 2020-11-17 23:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0012_auto_20201020_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
